### PR TITLE
Release update with Japanese Translations, updated instructions and FAQs

### PR DESCRIPTION
**Pull request by abhijitvalluri**
Updated the setup instructions a little bit, and added a lot more troubleshooting information to help users facing issues with notifications. Hopefully these changes will lead to faster troubleshooting and lesser support emails! 😃

### CODE REVIEW

**Comment by abhijitvalluri** [comment]
@YoshihideSogawa please take a look at this PR. See if you can add commits to this branch. If not, then let me know and I will see if I need to change some setting in github.

**Comment by YoshihideSogawa** [comment]
@abhijitvalluri I could not push to this branch

error log in sourcetree
```
update_japanese_translations:refs/heads/update_japanese_translations 
Pushing to https://github.com/abhijitvalluri/fitnotifications
remote: Permission to abhijitvalluri/fitnotifications.git denied to YoshihideSogawa.
fatal: unable to access 'https://github.com/abhijitvalluri/fitnotifications/': The requested URL returned error: 403
Completed with errors, see above
```

**Comment by abhijitvalluri** [comment]
I'll look into it. In the meantime please push it to your forked repo.

**Comment by abhijitvalluri** [comment]
@YoshihideSogawa, I added you as a collaborator for this repository. Please look for the email from github and accept the invitation. You can then push commits to this repo and this PR.

**Comment by abhijitvalluri** [comment]
@YoshihideSogawa looks good so far, but there are more strings that I changed since previous version. Will you be updating the translations for them too? If so, let me know once you are done with all translations so that we can move ahead and merge these changes and release an update.

**Comment by YoshihideSogawa** [comment]
@abhijitvalluri This change is just a test of push.I will continue to translate the app.
I will tell you in the mention once all work is done.

**Comment by YoshihideSogawa** [comment]
@abhijitvalluri 
My work has been completed! 😃

**Comment by abhijitvalluri** [comment]
Merged! And published update! :)

**Pull request merged**
