### PR TITLE
Extracted ICU4J code into a separate module and updated to version 58.2

### PR DESCRIPTION
**Pull request by sabi0**

### CODE REVIEW

**Review by abhijitvalluri — CHANGES_REQUESTED** [review]
A lot of vital resource files are missing in your commit at:
icu4j/src/main/resources/com/ibm/icu/impl/data/icudt58b/

Please take a look at the resources that are currently available in the master at:
app/src/main/resources/com/ibm/icu/impl/data/icudt57b/

And ensure that all those exist. Without all these language files, it __will__ cause Exceptions and crash the app. It may be acceptable for you but for others who may want to translate languages that are not present, it will cause the app to crash and give a very poor user experience.

**Comment by sabi0** [comment]
First of all, it will never crash. Remember that `catch (Exception e)`? The worst thing that could happen is that the original text will be used in the notification instead of the transliterated one.

Secondly, I specifically added a unit test to see that text in various languages can be successfully transliterated - see `TransliterationTest.java`.

And finally, all those 'en_US.res' files contain things like date formats, currency symbols, decimal separators, etc. They have no relation to transliteration. Removing them however reduces the APK size by 1 MB.

**Comment by abhijitvalluri** [comment]
Firstly, the unit tests are not comprehensive and only test Russian, Japanese, Greek, Thai, Arabic, Korean and Chinese. Secondly, I remember that you originally provided me with a stripped version of the library that could translate these languages as you claimed, but users noticed crashes when they were trying to translate other languages. I needed to add the extra resources to avoid those crashes. So, while this may not crash due to catching the exception, it will still not be ideal behavior. Is it better to save 1 MB at the expense of incorrect behavior (i.e. not correctly translating some languages) or is it better to have correct behavior? 1 MB is nothing these days.

**Comment by sabi0** [comment]
I've tried to cover as many language 'families' as I could think of in the tests. You are welcome to add more (e.g. for the languages the users were complaining about).

My point is that those *.res files will not improve transliteration in any meaningful way.

The files that could actually improve it are in the `brkitr` folder (e.g. `brkitr/thaidict.dict`). But it's not in the master. (that is why the Thai test is `@Ignore`-d).

Overall, `brkitr` will add another 2 MB (or even 4 if `cjdict.dict` is included). And still not every language will be (fully) transliterated.
For example, ICU4J does not transliterate some Russian symbols to Latin. So I was going to create a pull request with a custom conversion layer on top of ICU4J to get rid of "empty squares" on Fitbit.

**Review by abhijitvalluri — APPROVED** [review]

**Pull request merged**
