### PR TITLE
Added specialized message extractors for Telegram and WhatsApp

### PR DESCRIPTION
**Pull request by sabi0**
The 'extractors' utilize the knowledge of the Telegram / WhatsApp notifications patterns to retrieve the most useful data for sending to Fitbit.

The mechanism allows easy addition of 'extractors' for other applications.

The notifications from the apps without custom 'extractor' are processed by the previous "generic" code that has been moved to `GenericMessageExtractor`.

### CODE REVIEW

**Comment by sabi0** [comment]
Please do not merge this yet.
Apparently there is a strange error (likely due to the commit 67aca33) that causes the service to fail on start.
I am trying to figure it out.

**Comment by sabi0** [comment]
Actually the code in this PR is fine. It was some local issue on my phone (corrupted config?).

The same service startup failure was happening to a clean build off the master branch.
So I had to uninstall the app, reboot the phone (otherwise it was still picking up the old config after installation) and install it anew.

I've added some extra safeguard try-catch blocks in the last commit though. To make sure parsing the potentially invalid (localized) regexps won't crash the application.

**Comment by abhijitvalluri** [comment]
Let me know when this feature is ready and you are done making changes.

**Comment by sabi0** [comment]
I can take a pause.

I thought it was finished a few days ago already. But then I realized that it would be nice not to miss repeating daily Calendar notifications. So I've added that.
Then I received a bunch of photos in Telegram and saw "sent you a photo sent you a photo sent you a photo" on my Fitbit. So I've decided to optimize that too.
You know how it goes. Improvement never ends.

But feel free to integrate these changes into master. And I will then create a new branch and PR for further updates.

**Comment by benjymous** [comment]
In my code I've implemented an extractor for "Now Playing" type messages - now my issue is that the code will need to be updated to include the package name of every possible music player under the sun, which seems a bit unfriendly to the user.

I can recognise a media type message by the presence of the key Notification.EXTRA_MEDIA_SESSION inside the extras bundle, so was wondering if it made sense to extend the extractors logic to allow it to match an extractor based on bundle keys, to catch any media message from any enabled app.

So, instead if getMessageExtractor fails to find a registered extractor based on package name, it'll loop over each extractor in turn, and ask it "can you process this bundle?"

Does that make sense?

**Comment by sabi0** [comment]
Frankly speaking I wouldn't make things more complex than needed.
I'd just add this "now playing" extraction logic to the "generic" extractor.

So as soon as the user adds a music app to the selection he'll start receiving notifications.
No extra preferences, clean and simple.

And in case some app would need both a special extractor and "now playing", that special extractor will take care of that.
(You could put the actual "now playing" extraction logic to "basic" extractor. So that it's easily available to sub-classes. And "wire it in" in the "generic" extractor.)

**Comment by abhijitvalluri** [comment]
Sorry for the delay in accepting this. I was just focused on work and put this aside for a while.

**Pull request merged**
